name: Daily Updates

on:
  # Schedule workflow to run once daily at 4:20am
#  schedule:
#    - cron: '20 4 * * *'
  # Run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
    contents: write

# Workflow jobs can run sequentially or in parallel
# This workflow contains a single job called "update"
# The job itself contains 5 steps
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Installs latest stable version of python
      - uses: actions/setup-python@v5
        with:
            python-version: '3.x'

      - name: Install pip dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi

      - name: Generate new descriptions
        run: python src/main.py
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit updates
        run: |
            git config --global user.name "$GIT_USER"
            git config --global user.email $GIT_EMAIL
            git commit -am "Update"
            git push
        env:
            GIT_USER: Toronto Map
            GIT_EMAIL: toronto-map@noreply.github.com
